### PR TITLE
fix(repository-shorthand): support repo provider prefix

### LINKED ISSUE #1431: 🐛 Bug: `repository-shorthand` fixer doesn't support repo provider prefix
### Bug Report Checklist

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Given:

```json
{
  "repository": "github:patrik-csak/patrikcsak.com"
}
```

When I run `eslint --fix`, I expect the `repository` property to become:

```json
{
  "repository": {
    "type": "git",
    "url": "https://github.com/patrik-csak/patrikcsak.com"
  }
}
```

### Actual

```json
{
  "repository": {
  "type": "git",
  "url": "https://github.com/github:patrik-csak/patrikcsak.com"
}
}
```

The URL is incorrect (it includes `github:`) and the indentation of the new code isn't consistent with the existing indentation in `package.json`

### Version

0.85.0

### ESLint Version

9.39.1

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by michaelfaith**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1431
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This change updates all fixers to support different repo providers, and the providers prefix in general.  Now if you have repo defined in object syntax with either bitbucket, gitlab, github, or gist urls, the fixer will construct a shorthand string using the corresponding provider prefix.  On the other side, if you have repo defined as a shorthand and have configured to prefer object, it'll use the correct url based on the provider prefix, if specified (assume github if not).

### CODE REVIEW

File: src/rules/repository-shorthand.ts [hunk 1]
```diff
@@ -4,13 +4,57 @@ import { createRule } from "../createRule.ts";
...
+
+const getProviderFromUrl = (url: string): null | Provider => {
+	for (const provider of providers) {
+		if (providerRegexes[provider].test(url)) {
+			return provider;
+		}
+	}
+
+	return null;
+};
```
Comment (JoshuaKGoldberg) [inline src/rules/repository-shorthand.ts]: [Style] Nit: code golfing just a little bit, if you want. Definitely not a blocker at all IMO.

```suggestion
const getProviderFromUrl = (url: string) => {
	return providers.find((provider) => providerRegexes[provider].test(url));
};
```
